server:
  port: 8888

spring:
   cloud:
      discovery:
         enabled:false
   datasource:
     url: jdbc:mysql://192.168.19.202:3306/ppsearch?verifyServerCertificate=false&useSSL=false&requireSSL=false&characterEncoding=UTF-8&useUnicode=true
     username: collinson
     password: iclp2018

redis:
    ip:
         192.168.19.200


logging:
  file: /wxlog/ppsearch.log


#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
